### ISSUE TITLE
Persistence Unit Name for SchemaTool

### ISSUE THREAD

**Issue by dtsw** [datanucleus/datanucleus-eclipse-plugin#5]
I did not find a way to supply my Persistence Unit Name to the Schema Tool Job. The entered String is somehow ignored.
Basically i try to achieve the following command:

java -cp %CLASSPATH% org.datanucleus.store.schema.SchemaTool -v -create -pu TEST

The schema is created properly when i run this command on command line (the classpath is omitted here to be shorter). But the schema is created without honoring my package-h2.orm File when run via plugin. It seems it is not properly handling the Persistence Unit String and instead expects me to fill everything as arguments. If i dont, it complains about "There is no available StoreManager of type """. However, i was able to successfully use the plugin for schema creation by suppying all the connection properties and by adding "javax.jdo.option.Mapping" as an additional VM args in the options. It would be nicer if it would read my persistence.xml, because all the values are there already.

**Comment by andyjefferson** [comment]
Specification of persistence unit is defined clearly in the docs 
http://www.datanucleus.org:15080/products/accessplatform_5_2/jpa/tools.html#eclipse_preferences_schematool

**Comment by dtsw** [comment]
My issue is, i entered the Persistence Unit name there, but still have to enter Datastore details although they are defined in the Persistence Unit xml. So, it is by design that the Enhancer and the Schema Tool work differently?

**Comment by andyjefferson** [comment]
Yes. By design. Written long before "persistence.xml" even existed. But then it is open source so you can get the code and improve it

**Comment by dtsw** [comment]
ok thanks, i will see what i can do ;)

**Comment by andyjefferson** [comment]
Thx for your contrib
